// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpivyrzcybfakxkvcrzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwaXZ5cnpjeWJmYWt4a3ZjcnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTI3NzEsImV4cCI6MjA3MTU4ODc3MX0.OaytFDIRLR_7t6hy6PL7YR_OIYLo9D2hzgdcttvKNBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});